-- CreateTable
CREATE TABLE `RAW_MATERIALS` (
    `id` BIGINT NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `SKU` VARCHAR(191) NOT NULL,
    `quantity` INTEGER NOT NULL,
    `price` DECIMAL(65, 30) NOT NULL,
    `image` VARCHAR(191) NULL,
    `description` VARCHAR(191) NULL,
    `expiry_date` DATETIME(3) NOT NULL,
    `quality_status` ENUM('GOOD', 'AVERAGE', 'POOR') NOT NULL,
    `storage_location` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    INDEX `RAW_MATERIALS_SKU_idx`(`SKU`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SHOPIFY_VARIANTS` (
    `id` BIGINT NOT NULL,
    `productId` BIGINT NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `AvailableQty` INTEGER NOT NULL,
    `img` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,
    `variantName` VARCHAR(191) NULL,
    `variantOption` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `VARIANT_RAW_MATERIALS_TRACKER` (
    `variantId` BIGINT NOT NULL,
    `rawMaterialId` BIGINT NOT NULL,
    `avgQuantity` DECIMAL(65, 30) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    PRIMARY KEY (`variantId`, `rawMaterialId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CATEGORIES` (
    `id` INTEGER NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SHOPIFY_PRODUCTS` (
    `id` BIGINT NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `categoryId` INTEGER NOT NULL,
    `price` DECIMAL(65, 30) NOT NULL,
    `status` VARCHAR(191) NULL,
    `img` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RM_TRANSACTIONS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `rawMaterialId` BIGINT NOT NULL,
    `quantity` INTEGER NOT NULL,
    `transactionType` ENUM('IN', 'OUT', 'CREDITED', 'DEBITED') NOT NULL,
    `reason` VARCHAR(191) NOT NULL,
    `status` VARCHAR(191) NOT NULL,
    `initiatedById` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    INDEX `RM_TRANSACTIONS_status_idx`(`status`),
    INDEX `RM_TRANSACTIONS_transactionType_createdAt_idx`(`transactionType`, `createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RM_QC` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `transactionId` INTEGER NOT NULL,
    `rawMaterialId` BIGINT NOT NULL,
    `quality_status` ENUM('GOOD', 'AVERAGE', 'POOR') NOT NULL,
    `checkedById` INTEGER NOT NULL,
    `doneById` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RM_WASTAGE_LOGS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `transactionId` INTEGER NOT NULL,
    `rawMaterialId` BIGINT NOT NULL,
    `quantity` INTEGER NOT NULL,
    `reason` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Employee` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `role` ENUM('ADMIN', 'EMPLOYEE') NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `WIP` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `orderId` INTEGER NOT NULL,
    `status` ENUM('IN_PROGRESS', 'COMPLETED', 'FAILED') NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `WIP_PRODUCTS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `wipId` INTEGER NOT NULL,
    `productId` BIGINT NOT NULL,
    `quantity` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `WIPRawMaterial` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `wipId` INTEGER NOT NULL,
    `rawMaterialId` BIGINT NOT NULL,
    `quantity` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `FG` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `orderId` INTEGER NOT NULL,
    `customerName` VARCHAR(191) NOT NULL,
    `price` DECIMAL(65, 30) NOT NULL,
    `status` ENUM('IN_PROGRESS', 'COMPLETED', 'FAILED') NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `deliveryDate` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `FG_PRODUCTS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `fgId` INTEGER NOT NULL,
    `productId` INTEGER NOT NULL,
    `quantity` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `WIP_TRANSACTIONS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `wipId` INTEGER NOT NULL,
    `quantity` INTEGER NOT NULL,
    `transactionType` ENUM('IN', 'OUT', 'CREDITED', 'DEBITED') NOT NULL,
    `reason` VARCHAR(191) NOT NULL,
    `status` ENUM('IN_PROGRESS', 'COMPLETED', 'FAILED') NOT NULL,
    `initiatedById` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `WIP_TRANSACTIONS_status_idx`(`status`),
    INDEX `WIP_TRANSACTIONS_transactionType_createdAt_idx`(`transactionType`, `createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `FG_TRANSACTIONS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `fgId` INTEGER NOT NULL,
    `quantity` INTEGER NOT NULL,
    `transactionType` ENUM('IN', 'OUT', 'CREDITED', 'DEBITED') NOT NULL,
    `status` ENUM('IN_PROGRESS', 'COMPLETED', 'FAILED') NOT NULL,
    `reason` VARCHAR(191) NOT NULL,
    `IntiatedById` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    INDEX `FG_TRANSACTIONS_status_idx`(`status`),
    INDEX `FG_TRANSACTIONS_transactionType_createdAt_idx`(`transactionType`, `createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `WIP_QC` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `transactionId` INTEGER NOT NULL,
    `transactionType` ENUM('IN', 'OUT', 'CREDITED', 'DEBITED') NOT NULL,
    `wipId` INTEGER NOT NULL,
    `quality_status` ENUM('GOOD', 'AVERAGE', 'POOR') NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `FG_QC` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `transactionId` INTEGER NOT NULL,
    `transactionType` ENUM('IN', 'OUT', 'CREDITED', 'DEBITED') NOT NULL,
    `fgId` INTEGER NOT NULL,
    `quality_status` ENUM('GOOD', 'AVERAGE', 'POOR') NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `WIP_WASTAGE_LOGS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `transactionId` INTEGER NOT NULL,
    `transactionType` ENUM('IN', 'OUT', 'CREDITED', 'DEBITED') NOT NULL,
    `wipId` INTEGER NOT NULL,
    `quantity` INTEGER NOT NULL,
    `reason` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `FG_WASTAGE_LOGS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `transactionId` INTEGER NOT NULL,
    `transactionType` ENUM('IN', 'OUT', 'CREDITED', 'DEBITED') NOT NULL,
    `fgId` INTEGER NOT NULL,
    `quantity` INTEGER NOT NULL,
    `reason` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AuditLogs` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `tableName` VARCHAR(191) NOT NULL,
    `action` ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL,
    `oldValue` JSON NULL,
    `newValue` JSON NULL,
    `changedById` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `SHOPIFY_VARIANTS` ADD CONSTRAINT `SHOPIFY_VARIANTS_productId_fkey` FOREIGN KEY (`productId`) REFERENCES `SHOPIFY_PRODUCTS`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `VARIANT_RAW_MATERIALS_TRACKER` ADD CONSTRAINT `VARIANT_RAW_MATERIALS_TRACKER_variantId_fkey` FOREIGN KEY (`variantId`) REFERENCES `SHOPIFY_VARIANTS`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `VARIANT_RAW_MATERIALS_TRACKER` ADD CONSTRAINT `VARIANT_RAW_MATERIALS_TRACKER_rawMaterialId_fkey` FOREIGN KEY (`rawMaterialId`) REFERENCES `RAW_MATERIALS`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SHOPIFY_PRODUCTS` ADD CONSTRAINT `SHOPIFY_PRODUCTS_categoryId_fkey` FOREIGN KEY (`categoryId`) REFERENCES `CATEGORIES`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RM_TRANSACTIONS` ADD CONSTRAINT `RM_TRANSACTIONS_rawMaterialId_fkey` FOREIGN KEY (`rawMaterialId`) REFERENCES `RAW_MATERIALS`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RM_TRANSACTIONS` ADD CONSTRAINT `RM_TRANSACTIONS_initiatedById_fkey` FOREIGN KEY (`initiatedById`) REFERENCES `Employee`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RM_QC` ADD CONSTRAINT `RM_QC_rawMaterialId_fkey` FOREIGN KEY (`rawMaterialId`) REFERENCES `RAW_MATERIALS`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RM_QC` ADD CONSTRAINT `RM_QC_transactionId_fkey` FOREIGN KEY (`transactionId`) REFERENCES `RM_TRANSACTIONS`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RM_QC` ADD CONSTRAINT `RM_QC_checkedById_fkey` FOREIGN KEY (`checkedById`) REFERENCES `Employee`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RM_QC` ADD CONSTRAINT `RM_QC_doneById_fkey` FOREIGN KEY (`doneById`) REFERENCES `Employee`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RM_WASTAGE_LOGS` ADD CONSTRAINT `RM_WASTAGE_LOGS_rawMaterialId_fkey` FOREIGN KEY (`rawMaterialId`) REFERENCES `RAW_MATERIALS`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RM_WASTAGE_LOGS` ADD CONSTRAINT `RM_WASTAGE_LOGS_transactionId_fkey` FOREIGN KEY (`transactionId`) REFERENCES `RM_TRANSACTIONS`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `WIP_PRODUCTS` ADD CONSTRAINT `WIP_PRODUCTS_wipId_fkey` FOREIGN KEY (`wipId`) REFERENCES `WIP`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `WIP_PRODUCTS` ADD CONSTRAINT `WIP_PRODUCTS_productId_fkey` FOREIGN KEY (`productId`) REFERENCES `SHOPIFY_PRODUCTS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `WIPRawMaterial` ADD CONSTRAINT `WIPRawMaterial_wipId_fkey` FOREIGN KEY (`wipId`) REFERENCES `WIP`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `WIPRawMaterial` ADD CONSTRAINT `WIPRawMaterial_rawMaterialId_fkey` FOREIGN KEY (`rawMaterialId`) REFERENCES `RAW_MATERIALS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FG_PRODUCTS` ADD CONSTRAINT `FG_PRODUCTS_fgId_fkey` FOREIGN KEY (`fgId`) REFERENCES `FG`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `WIP_TRANSACTIONS` ADD CONSTRAINT `WIP_TRANSACTIONS_wipId_fkey` FOREIGN KEY (`wipId`) REFERENCES `WIP`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `WIP_TRANSACTIONS` ADD CONSTRAINT `WIP_TRANSACTIONS_initiatedById_fkey` FOREIGN KEY (`initiatedById`) REFERENCES `Employee`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FG_TRANSACTIONS` ADD CONSTRAINT `FG_TRANSACTIONS_fgId_fkey` FOREIGN KEY (`fgId`) REFERENCES `FG`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FG_TRANSACTIONS` ADD CONSTRAINT `FG_TRANSACTIONS_IntiatedById_fkey` FOREIGN KEY (`IntiatedById`) REFERENCES `Employee`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `WIP_QC` ADD CONSTRAINT `WIP_QC_wipId_fkey` FOREIGN KEY (`wipId`) REFERENCES `WIP`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `WIP_QC` ADD CONSTRAINT `WIP_QC_transactionId_fkey` FOREIGN KEY (`transactionId`) REFERENCES `WIP_TRANSACTIONS`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FG_QC` ADD CONSTRAINT `FG_QC_fgId_fkey` FOREIGN KEY (`fgId`) REFERENCES `FG`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FG_QC` ADD CONSTRAINT `FG_QC_transactionId_fkey` FOREIGN KEY (`transactionId`) REFERENCES `FG_TRANSACTIONS`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `WIP_WASTAGE_LOGS` ADD CONSTRAINT `WIP_WASTAGE_LOGS_wipId_fkey` FOREIGN KEY (`wipId`) REFERENCES `WIP`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `WIP_WASTAGE_LOGS` ADD CONSTRAINT `WIP_WASTAGE_LOGS_transactionId_fkey` FOREIGN KEY (`transactionId`) REFERENCES `WIP_TRANSACTIONS`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FG_WASTAGE_LOGS` ADD CONSTRAINT `FG_WASTAGE_LOGS_fgId_fkey` FOREIGN KEY (`fgId`) REFERENCES `FG`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FG_WASTAGE_LOGS` ADD CONSTRAINT `FG_WASTAGE_LOGS_transactionId_fkey` FOREIGN KEY (`transactionId`) REFERENCES `FG_TRANSACTIONS`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `AuditLogs` ADD CONSTRAINT `AuditLogs_changedById_fkey` FOREIGN KEY (`changedById`) REFERENCES `Employee`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
